In [18]:
import pandas as pd 
import numpy as np 
import plotly.express as px 
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import RobustScaler 
from sklearn.model_selection import cross_validate 
from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier 
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import recall_score , precision_score , f1_score , classification_report

In [19]:
df =  pd.read_csv('advertising.csv')
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   str
 5   City                      1000 non-null   str
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   str
 8   Timestamp                 1000 non-null   str
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 151.1 KB

In [21]:
df.describe().round(2)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Clicked on Ad
count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.0
mean,65.00,36.01,55000.00,180.00,0.48,0.5
std,15.85,8.79,13414.63,43.90,0.50,0.5
min,32.60,19.00,13996.50,104.78,0.00,0.0
25%,51.36,29.00,47031.80,138.83,0.00,0.0
50%,68.22,35.00,57012.30,183.13,0.00,0.5
75%,78.55,42.00,65470.63,218.79,1.00,1.0
max,91.43,61.00,79484.80,269.96,1.00,1.0

In [22]:
df.describe(include='str')

,Ad Topic Line,City,Country,Timestamp
count,1000,1000,1000,1000
unique,1000,969,237,1000
top,Cloned 5thgeneration orchestration,Lisamouth,Czech Republic,2016-03-27 00:53:11
freq,1,3,9,1

In [23]:
df.drop(['Ad Topic Line' ,'City' , 'Timestamp'] , axis=1 ,  inplace=True)

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Country,Clicked on Ad
0,68.95,35,61833.90,256.09,0,Tunisia,0
1,80.23,31,68441.85,193.77,1,Nauru,0
2,69.47,26,59785.94,236.50,0,San Marino,0
3,74.15,29,54806.18,245.89,1,Italy,0
4,68.37,35,73889.99,225.58,0,Iceland,0

In [26]:
x = df.drop('Clicked on Ad' , axis=1)
y = df['Clicked on Ad']

In [27]:
num_col = x.select_dtypes('number').drop('Male' , axis=1 ).columns
num_col

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage'],
      dtype='str')

In [28]:
num_pipline = Pipeline([('scaler' , RobustScaler())])
num_pipline

Pipeline(steps=[('scaler', RobustScaler())])

In [29]:
from category_encoders import BinaryEncoder

binary = BinaryEncoder()

binary_pipline = Pipeline([('binary' , binary)])
binary_pipline

Pipeline(steps=[('binary', BinaryEncoder())])

In [30]:
cat_col = ['Country']

In [31]:
from sklearn.compose import ColumnTransformer 
prepressing = ColumnTransformer([
    ('num' , num_pipline , num_col),
    ('cat' , binary_pipline , cat_col)],
    remainder='passthrough'
    )
prepressing

ColumnTransformer(remainder='passthrough',
                  transformers=[('num',
                                 Pipeline(steps=[('scaler', RobustScaler())]),
                                 Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage'],
      dtype='str')),
                                ('cat',
                                 Pipeline(steps=[('binary', BinaryEncoder())]),
                                 ['Country'])])

In [32]:
models = [('LogisticRegression',LogisticRegression(random_state=42 , n_jobs=-1)),
          ('KNeighborsClassifier',KNeighborsClassifier()),
          ('GaussianNB',GaussianNB()),
          ('SVC',SVC(kernel='rbf',random_state=42)),
          ('SVC',SVC(kernel='linear',random_state=42)),
          ('DecisionTreeClassifier',DecisionTreeClassifier(random_state=42,)),
          ('RandomForestClassifier',RandomForestClassifier(random_state=42,n_jobs=-1)),
          ('XGBClassifier',XGBClassifier(random_state=42, n_jobs=-1)),
          ('CatBoostClassifier',CatBoostClassifier(verbose=0,random_state=42)),
          ('LGBMClassifier',LGBMClassifier(random_state=42, n_jobs=-1, verbose=-1))

          ]

for model in models:
    model_pipeline = Pipeline(steps=[('preprocessing' , prepressing),
                                     ('model' , model[1])])
    cv = cross_validate(model_pipeline , X=x , y=y , cv=5 , scoring=['accuracy','recall' , 'precision' , 'f1'] , n_jobs=-1 , return_train_score=True )

    print(f"Model : {model[0]}")
    print(f"Train Accuracy : {cv['train_accuracy'].mean()*100}")
    print(f"Test Accuracy : {cv['test_accuracy'].mean()*100} \n")

    print(f"Train Recall : {cv['train_recall'].mean()*100}")
    print(f"Test Recall : {cv['test_recall'].mean()*100} \n")

    print(f"Train Precision : {cv['train_precision'].mean()*100}")
    print(f"Test Precision : {cv['test_precision'].mean()*100} \n") 

    print(f"Train F1 : {cv['train_f1'].mean()*100}")
    print(f"Test F1 : {cv['test_f1'].mean()*100} \n")
    
    print("-" * 50)

Model : LogisticRegression
Train Accuracy : 97.19999999999999
Test Accuracy : 97.0

Train Recall : 95.89999999999999
Test Recall : 95.8

Train Precision : 98.46005450004778
Test Precision : 98.16208398252918

Train F1 : 97.16261679808025
Test F1 : 96.94879018724511

--------------------------------------------------
Model : KNeighborsClassifier
Train Accuracy : 95.42500000000001
Test Accuracy : 94.80000000000001

Train Recall : 91.95
Test Recall : 90.99999999999999

Train Precision : 98.8170898383067
Test Precision : 98.48620959815307

Train F1 : 95.2576503579104
Test F1 : 94.5686974715642

--------------------------------------------------
Model : GaussianNB
Train Accuracy : 96.675
Test Accuracy : 96.50000000000001

Train Recall : 96.35000000000001
Test Recall : 96.2

Train Precision : 96.98198089770635
Test Precision : 96.80173143008194

Train F1 : 96.66369877709329
Test F1 : 96.48085670816549

--------------------------------------------------
Model : SVC
Train Accuracy : 98.25
Test Accuracy : 96.1

Train Recall : 96.95
Test Recall : 94.39999999999999

Train Precision : 99.5379192920144
Test Precision : 97.7503583281341

Train F1 : 98.22597152426538
Test F1 : 96.0210504750069

--------------------------------------------------
Model : SVC
Train Accuracy : 97.37499999999999
Test Accuracy : 96.89999999999999

Train Recall : 96.29999999999998
Test Recall : 96.0

Train Precision : 98.41702844033142
Test Precision : 97.76781586420975

Train F1 : 97.3463298081535
Test F1 : 96.85965922419125

--------------------------------------------------
Model : DecisionTreeClassifier
Train Accuracy : 100.0
Test Accuracy : 93.10000000000001

Train Recall : 100.0
Test Recall : 94.79999999999998

Train Precision : 100.0
Test Precision : 91.84340684068405

Train F1 : 100.0
Test F1 : 93.22891664128339

--------------------------------------------------
Model : RandomForestClassifier
Train Accuracy : 100.0
Test Accuracy : 96.1

Train Recall : 100.0
Test Recall : 95.60000000000001

Train Precision : 100.0
Test Precision : 96.6124630653662

Train F1 : 100.0
Test F1 : 96.073343428258

--------------------------------------------------
Model : XGBClassifier
Train Accuracy : 100.0
Test Accuracy : 95.0

Train Recall : 100.0
Test Recall : 94.39999999999999

Train Precision : 100.0
Test Precision : 95.63033383864777

Train F1 : 100.0
Test F1 : 94.97391792427082

--------------------------------------------------
Model : CatBoostClassifier
Train Accuracy : 99.9
Test Accuracy : 95.89999999999999

Train Recall : 99.8
Test Recall : 95.0

Train Precision : 100.0
Test Precision : 96.78744869151957

Train F1 : 99.89981210849402
Test F1 : 95.86119522085191

--------------------------------------------------
Model : LGBMClassifier
Train Accuracy : 100.0
Test Accuracy : 95.5

Train Recall : 100.0
Test Recall : 95.0

Train Precision : 100.0
Test Precision : 95.96749809677195

Train F1 : 100.0
Test F1 : 95.46671214232104

--------------------------------------------------

In [37]:
finally_model = Pipeline(steps=[('preprocessing' , prepressing),
                               ('model' , LogisticRegression(random_state=42 , n_jobs=-1))])
finally_model.fit(x , y)

c:\Users\memoj\anaconda3\envs\AI\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   RobustScaler())]),
                                                  Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('binary',
                                                                   BinaryEncoder())]),
                                                  ['Country'])])),
                ('model', LogisticRegression(n_jobs=-1, random_state=42))])

In [65]:
print(finally_model.predict(x.sample(random_state=42))[0])

1

In [73]:
finally_model.predict_proba(x.sample(random_state=42)).round(3)[0][1]*100

np.float64(97.2)

In [57]:
finally_model.classes_

array([0, 1])

In [74]:
import joblib
joblib.dump(finally_model , 'final_model.pkl')

['final_model.pkl']

In [75]:
df.to_csv('cleaned.csv')

In [3]:
import streamlit as st

In [35]:
! streamlit run Home.py

^C

In [2]:
!pip install pipreqs

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [1]:
import pipreqs

ModuleNotFoundError: No module named 'pipreqs'